# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA BSR Theorist
repo_url: 'https://github.com/autoresearch/autora-theorist-bsr'

nav:
- Home: 'index.md'
- Quickstart: 'quick-start.md'
- How it works: 'how-it-works.md'
- Meta parameters: 'meta-parameters.md'
- Search space: 'search-space.md'
- Examples:
    - Basic usage: 'basic-usage.ipynb'